input=carddata.txt
convert_book = {
    ' Luke': ' Luke'
    '': ''
    '1 Kings': '1 Kings'
    '1 Samuel': '1 Samuel'
    '2 Kings': '2 Kings'
    '2 Samuel': '2 Samuel'
    '3 John': '3 John'
    'Acts ': 'Acts '
    'Acts 8:32;Isaiah': 'Acts 8:32;Isaiah'
    'Acts': 'Acts'
    'Amos ': 'Amos '
    'Amos': 'Amos'
    'COlossains': 'COlossains'
    'Colossains': 'Colossains'
    'Colossians': 'Colossians'
    'Daniel': 'Daniel'
    'Deuteronomy 21:22-23/Galatians': 'Deuteronomy 21:22-23/Galatians'
    'Deuteronomy': 'Deuteronomy'
    'Deutoronomy': 'Deutoronomy'
    'Ecclesiastes': 'Ecclesiastes'
    'Ephesians': 'Ephesians'
    'Esther': 'Esther'
    'Exodus': 'Exodus'
    'Ezekiel ': 'Ezekiel '
    'Ezekiel': 'Ezekiel'
    'Ezra': 'Ezra'
    'Galatians': 'Galatians'
    'Genesis 12:3/Acts': 'Genesis 12:3/Acts'
    'Genesis': 'Genesis'
    'Habakkuk': 'Habakkuk'
    'Haggai': 'Haggai'
    'Hebrews ': 'Hebrews '
    'Hebrews (Exodus) 12 (19):20': 'Hebrews (Exodus) 12 (19):20'
    'Hebrews (Jeremiah) 8 (31):12': 'Hebrews (Jeremiah) 8 (31):12'
    'Hebrews (Jeremiah) 8 (31):9': 'Hebrews (Jeremiah) 8 (31):9'
    'Hebrews (Psalm) 1 (45):9': 'Hebrews (Psalm) 1 (45):9'
    'Hebrews (Psalm) 3 (95):15': 'Hebrews (Psalm) 3 (95):15'
    'Hebrews (Psalm) 3 (95):7-8': 'Hebrews (Psalm) 3 (95):7-8'
    'Hebrews (Psalm) 4 (95):7': 'Hebrews (Psalm) 4 (95):7'
    'Hebrews 12:20  Exodus': 'Hebrews 12:20  Exodus'
    'Hebrews 1:11-12  Psalm': 'Hebrews 1:11-12  Psalm'
    'Hebrews 1:9  Psalm': 'Hebrews 1:9  Psalm'
    'Hebrews 3:15  Psalm': 'Hebrews 3:15  Psalm'
    'Hebrews 3:7-8  Psalm': 'Hebrews 3:7-8  Psalm'
    'Hebrews 4:7  Psalm': 'Hebrews 4:7  Psalm'
    'Hebrews 8:9  Jeremiah': 'Hebrews 8:9  Jeremiah'
    'Hebrews': 'Hebrews'
    'Hosea 11:1 (Matthew': 'Hosea 11:1 (Matthew'
    'Hosea': 'Hosea'
    'I  Kings': 'I  Kings'
    'I Chronicles': 'I Chronicles'
    'I Corinitians': 'I Corinitians'
    'I Corinthians 1:20,25 (Good); Proverbs 1:29, 32': 'I Corinthians 1:20,25 (Good); Proverbs 1:29, 32'
    'I Corinthians': 'I Corinthians'
    'I John ': 'I John '
    'I John': 'I John'
    'I Kings (I Kings)': 'I Kings (I Kings)'
    'I Kings': 'I Kings'
    'I Peter': 'I Peter'
    'I Sammuel': 'I Sammuel'
    'I Samuel ': 'I Samuel '
    'I Samuel': 'I Samuel'
    'I Thessalonians': 'I Thessalonians'
    'I Timothy': 'I Timothy'
    'II Chronicales ': 'II Chronicales '
    'II Chronicles (II Chronicles)': 'II Chronicles (II Chronicles)'
    'II Chronicles (II Kings)': 'II Chronicles (II Kings)'
    'II Chronicles': 'II Chronicles'
    'II Corinthians': 'II Corinthians'
    'II Corithians': 'II Corithians'
    'II John': 'II John'
    'II KIngs': 'II KIngs'
    'II Kigns': 'II Kigns'
    'II Kings (II Chronicles)': 'II Kings (II Chronicles)'
    'II Kings': 'II Kings'
    'II Peter': 'II Peter'
    'II Samuel': 'II Samuel'
    'II Thessalonians': 'II Thessalonians'
    'II Timothy': 'II Timothy'
    'III John': 'III John'
    'Isaiah (Romans)': 'Isaiah (Romans)'
    'Isaiah': 'Isaiah'
    'James (Proverbs)': 'James (Proverbs)'
    'James 4:6 (Proverbs': 'James 4:6 (Proverbs'
    'James': 'James'
    'Jeremiah 31:33 (Hebrews': 'Jeremiah 31:33 (Hebrews'
    'Jeremiah': 'Jeremiah'
    'Job': 'Job'
    'Joel': 'Joel'
    'John ': 'John '
    'John': 'John'
    'Jonah': 'Jonah'
    'Josephus': 'Josephus'
    'Josephus, Antiquities': 'Josephus, Antiquities'
    'Josephus, War of the Jews, Book VII, Chapter': 'Josephus, War of the Jews, Book VII, Chapter'
    'Joshua': 'Joshua'
    'Jude': 'Jude'
    'Judges': 'Judges'
    'Kings': 'Kings'
    'Lamentations': 'Lamentations'
    'Leviticus ': 'Leviticus '
    'Leviticus': 'Leviticus'
    'Luke': 'Luke'
    'Malachi ': 'Malachi '
    'Malachi 4:6 (Luke': 'Malachi 4:6 (Luke'
    'Malachi': 'Malachi'
    'Mark ': 'Mark '
    'Mark': 'Mark'
    'Matthew (Zechariah)': 'Matthew (Zechariah)'
    'Matthew 2:6/Micah': 'Matthew 2:6/Micah'
    'Matthew': 'Matthew'
    'Micah': 'Micah'
    'Nahum': 'Nahum'
    'Nehemiah': 'Nehemiah'
    'New': 'New'
    'Numbers': 'Numbers'
    'Obadiah': 'Obadiah'
    'Old': 'Old'
    'Philemon': 'Philemon'
    'Philippians': 'Philippians'
    'Phillipians': 'Phillipians'
    'Phillippians': 'Phillippians'
    'Proverbs': 'Proverbs'
    'Psalm 16:10 (Acts': 'Psalm 16:10 (Acts'
    'Psalm': 'Psalm'
    'Psalms': 'Psalms'
    'Revelation ': 'Revelation '
    'Revelation': 'Revelation'
    'Romans': 'Romans'
    'Ruth ': 'Ruth '
    'Ruth': 'Ruth'
    'Song of Solomon': 'Song of Solomon'
    'Titus': 'Titus'
    'Zechariah': 'Zechariah'
    'Zephaniah': 'Zephaniah'
}
