document.write('<script language="JavaScript">');
document.write("  var amzn_wdgt={widget:'MyFavorites'};");
document.write("  amzn_wdgt.tag='unistuboo-20';");
document.write("  amzn_wdgt.columns='1';");
document.write("  amzn_wdgt.rows='" + hscp_count + "';");
document.write("  amzn_wdgt.title='For Further Reading';");
document.write("  amzn_wdgt.width='175';");
document.write("  amzn_wdgt.ASIN='" + hscp_linklist + "';");
document.write("  amzn_wdgt.showImage='False';");
document.write("  amzn_wdgt.showPrice='False';");
document.write("  amzn_wdgt.showRating='True';");
document.write("  amzn_wdgt.design='1';");
document.write("  amzn_wdgt.colorTheme='Blues';");
document.write("  amzn_wdgt.outerBackgroundColor='#6DA6E2';");
document.write("  amzn_wdgt.borderColor='#5C95D1';");
document.write("  amzn_wdgt.headerTextColor='#FFFFFF';");
document.write("  amzn_wdgt.marketPlace='US';");
document.write("</script>");
document.write('<script language="JavaScript" type="text/javascript" src="http://wms.assoc-amazon.com/20070822/US/js/AmazonWidgets.js"></script>');

